global_vars = {
    'num_points':[100, 10, 10],
    'total_time':4000,
    'time_steps':4000,
    'bounds':[0, 1, 0, 0.1, 0, 0.1],
    'nbounds':3,
    'length':1.0,
    'width':0.1,
    'thick':0.1,
    'modulus':200.0,
    'boundary_direction':1,
    'loading_direction':[1, 2, 3],
    'applied_pressure':200.0,
    'dtemp':0.0,
    'volume':None,
    'area':None,
    'delta':None,
    'dx':None,
    'bond_constant':None}